version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 7
  - package-ecosystem: "terraform"
    directories: 
    - "/infra"
    - "/infra/modules/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 7
