name: "CI-Deploy"
on:
  workflow_dispatch:
    inputs:
      azd_environment_name:
        description: "Name of the AZD Environment"
        required: true
        default: "CICD"
      azure_location:
        description: "Azure location for the environment"
        required: true
        default: "eastus"
      run_azd_down:
        description: "Run AZD Down to destroy the deployed resources."
        type: boolean
        required: true
        default: false
  push:
    # Run when commits are pushed to mainline branch
    # Set this to the mainline branch you are using
    branches:
      - main
# GitHub Actions workflow to deploy to Azure using azd

permissions:
  actions: read # Needed for uploading SARIF reports
  security-events: write  # Needed for uploading SARIF reports
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ${{ fromJson(vars.ACTIONS_RUNNER_NAME || '["ubuntu-latest"]') }}
    env:
      AZURE_ENV_NAME: ${{ github.event.inputs.azd_environment_name || 'CICD' }}
      AZURE_LOCATION: ${{ github.event.inputs.azure_location || 'eastus' }}
      
    steps:
      - name: Checkout the branch ${{ github.ref_name }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref_name }}

      - name: Install azd
        uses: Azure/setup-azd@ae0f8b5482eeac61e940f447327d84c73beb8b1e # v2.1.0
        with:
          version: '1.17.2'  # Specify your desired azd version here

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0


      - name: Install TFLint
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
        with:
          tflint_version: v0.49.0
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Used to avoid rate

      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.17.0/gitleaks_8.17.0_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
          rm gitleaks.tar.gz
          gitleaks version

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: '8.0.x'

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@6c7b538671a040d11afd8ab94d77bfe3b3ed87e6 # v1.9.1
      
      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool --version 1.44.2
          pac help


      - name: Set Up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # 5.6.0
        with:
          python-version: "3.x"

      - name: Install Checkov
        run: pip install checkov

      - name: Login to Azure with Federated Identity
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        env:
          POWER_PLATFORM_USE_OIDC: "true"
          POWER_PLATFORM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          POWER_PLATFORM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

          ARM_USE_AZUREAD: "true"
          ARM_STORAGE_USE_AZUREAD: "true"
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          
          RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
          RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
          RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
          
          RESOURCE_SHARE_USER: ${{ vars.RESOURCE_SHARE_USER }}
      
          GITHUB_PAT: ${{ secrets.MCS_RUNNER }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_RUNNER_IMAGE_NAME: "github-runner"
          GITHUB_RUNNER_IMAGE_TAG: "latest"
          GITHUB_RUNNER_IMAGE_BRANCH: ${{ github.ref_name }}
        shell: bash
        run: |
          azd config set auth.useAzCliAuth "true"
          azd env new "$AZURE_ENV_NAME" --location "$AZURE_LOCATION" --no-prompt
          azd env set RESOURCE_SHARE_USER "$RESOURCE_SHARE_USER"

          azd env set RS_STORAGE_ACCOUNT "$RS_STORAGE_ACCOUNT"
          azd env set RS_CONTAINER_NAME "$RS_CONTAINER_NAME"
          azd env set RS_RESOURCE_GROUP "$RS_RESOURCE_GROUP"

          azd env set GITHUB_PAT "$GITHUB_PAT"
          azd env set GITHUB_REPO_OWNER "$GITHUB_REPO_OWNER"
          azd env set GITHUB_REPO_NAME "$GITHUB_REPO_NAME"
          azd env set GITHUB_RUNNER_IMAGE_NAME "$GITHUB_RUNNER_IMAGE_NAME"
          azd env set GITHUB_RUNNER_IMAGE_TAG "$GITHUB_RUNNER_IMAGE_TAG"
          azd env set GITHUB_RUNNER_IMAGE_BRANCH "$GITHUB_RUNNER_IMAGE_BRANCH"

          azd provision --no-prompt

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: success() || failure()
        with:
          name: sarif-reports
          path: |
            ./gitleaks-report.sarif
            ./checkov-results.sarif/results_sarif.sarif

      - name: Upload Gitleaks SARIF report to Github
        uses: github/codeql-action/upload-sarif@9b02dc2f60288b463e7a66e39c78829b62780db7 # v2.22.1
        with:
          sarif_file: ./gitleaks-report.sarif


      - name: Upload Checkov SARIF Report to GitHub
        uses: github/codeql-action/upload-sarif@9b02dc2f60288b463e7a66e39c78829b62780db7 # v2.22.1
        with:
          sarif_file: ./checkov-results.sarif/results_sarif.sarif

      - name: Azd down
        if: ${{ github.event.inputs.run_azd_down == 'true' }}
        env:
          POWER_PLATFORM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          POWER_PLATFORM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          POWER_PLATFORM_USE_OIDC: "true"

          ARM_USE_AZUREAD: "true"
          ARM_STORAGE_USE_AZUREAD: "true"
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

          RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
          RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
          RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
          RESOURCE_SHARE_USER: ${{ vars.RESOURCE_SHARE_USER }}
          
        shell: bash
        run: |
          azd env set RS_STORAGE_ACCOUNT "$RS_STORAGE_ACCOUNT"
          azd env set RS_CONTAINER_NAME "$RS_CONTAINER_NAME"
          azd env set RS_RESOURCE_GROUP "$RS_RESOURCE_GROUP"
          azd env set RESOURCE_SHARE_USER "$RESOURCE_SHARE_USER"

          azd env select "$AZURE_ENV_NAME"
          azd down --no-prompt --force --purge