name: "CI Destroy Resources"
on:
  push:
    branches:
      - "sbaidachni/azddown"
  workflow_dispatch:
    inputs:
      azd_environment_name:
        description: "Name of the AZD Environment"
        required: true
        default: "CICDsbaydach"

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_ENV_NAME: ${{ github.event.inputs.azd_environment_name || 'CICDsbaydach' }}

    steps:
      - name: Checkout the branch ${{ github.ref_name }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref_name }}

      - name: Install azd
        uses: Azure/setup-azd@ae0f8b5482eeac61e940f447327d84c73beb8b1e # v2.1.0
        with:
          version: '1.17.2'  # Specify your desired azd version here

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0

      - name: Login to Azure with Federated Identity
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Azd down
        env:
          POWER_PLATFORM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          POWER_PLATFORM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          POWER_PLATFORM_USE_OIDC: "true"

          ARM_USE_AZUREAD: "true"
          ARM_STORAGE_USE_AZUREAD: "true"
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

          RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
          RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
          RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
          RESOURCE_SHARE_USER: ${{ vars.RESOURCE_SHARE_USER }}
          
        shell: bash
        run: |
          azd config set auth.useAzCliAuth "true"
          azd env new "$AZURE_ENV_NAME" --no-prompt
          azd env set RS_STORAGE_ACCOUNT "$RS_STORAGE_ACCOUNT"
          azd env set RS_CONTAINER_NAME "$RS_CONTAINER_NAME"
          azd env set RS_RESOURCE_GROUP "$RS_RESOURCE_GROUP"
          azd env set RESOURCE_SHARE_USER "$RESOURCE_SHARE_USER"

          azd env select "$AZURE_ENV_NAME"
          azd down --no-prompt --force --purge
