name: "CI-Deploy"
on:
  workflow_dispatch:
    inputs:
      azd_environment_name:
        description: "Name of the AZD Environment"
        required: true
        default: "CICD"
      azure_location:
        description: "Azure location for the environment"
        required: true
        default: "eastus"
      run_azd_down:
        description: "Run AZD Down to destroy the deployed resources."
        type: boolean
        required: true
        default: false
  push:
    # Run when commits are pushed to mainline branch
    # Set this to the mainline branch you are using
    branches:
      - main
# GitHub Actions workflow to deploy to Azure using azd

permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_ENV_NAME: ${{ github.event.inputs.azd_environment_name || 'CICD' }}
      AZURE_LOCATION: ${{ github.event.inputs.azure_location || 'eastus' }}


    steps:
      - name: Checkout the branch ${{ github.ref_name }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref_name }}

      - name: Install azd
        uses: Azure/setup-azd@ae0f8b5482eeac61e940f447327d84c73beb8b1e # v2.1.0
        with:
          version: '1.17.2'  # Specify your desired azd version here

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.9.0


      - name: Install TFLint
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4.1.1
        with:
          tflint_version: v0.49.0
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Used to avoid rate

      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.17.0/gitleaks_8.17.0_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/
          rm gitleaks.tar.gz
          gitleaks version

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
        with:
          dotnet-version: '8.0.x'

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@51f663ea104eb227c3712215ceb2f82827d81c27 # v1.9.0

      - name: Test Power Platform CLI
        run: |
          PAC_PATH=$(find /tmp -type f -name pac -executable | head -n 1)
          if [ -z "$PAC_PATH" ]; then
            echo "PAC CLI not found!" >&2
            exit 1
          fi
          PAC_DIR=$(dirname "$PAC_PATH")
          echo "Found pac at $PAC_PATH"
          export PATH="$PAC_DIR:$PATH"
          pac help
          
      - name: Set Up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # 5.6.0
        with:
          python-version: "3.x"

      - name: Install Checkov
        run: pip install checkov

      - name: Login to Azure with Federated Identity
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        env:
          #POWER_PLATFORM_USE_CLI: false
        #  POWER_PLATFORM_USE_OIDC: "true"
          POWER_PLATFORM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          POWER_PLATFORM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

          ARM_USE_AZUREAD: "true"
          ARM_STORAGE_USE_AZUREAD: "true"
         # ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          
          RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
          RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
          RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
          
          RESOURCE_SHARE_USER: ${{ vars.RESOURCE_SHARE_USER }}
      
          GITHUB_PAT: ${{ secrets.MCS_RUNNER }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_RUNNER_IMAGE_NAME: "github-runner"
          GITHUB_RUNNER_IMAGE_TAG: "latest"
          GITHUB_RUNNER_IMAGE_BRANCH: ${{ github.ref_name }}
        shell: pwsh
        run: |
          azd config set auth.useAzCliAuth "true"
          azd env new $env:AZURE_ENV_NAME --location $env:AZURE_LOCATION --no-prompt
          azd env set RESOURCE_SHARE_USER "$env:RESOURCE_SHARE_USER"
          #azd env set POWER_PLATFORM_USE_CLI "false"

          azd env set RS_STORAGE_ACCOUNT $env:RS_STORAGE_ACCOUNT
          azd env set RS_CONTAINER_NAME $env:RS_CONTAINER_NAME
          azd env set RS_RESOURCE_GROUP $env:RS_RESOURCE_GROUP

          azd env set GITHUB_PAT $env:GITHUB_PAT
          azd env set GITHUB_REPO_OWNER $env:GITHUB_REPO_OWNER
          azd env set GITHUB_REPO_NAME $env:GITHUB_REPO_NAME
          azd env set GITHUB_RUNNER_IMAGE_NAME $env:GITHUB_RUNNER_IMAGE_NAME
          azd env set GITHUB_RUNNER_IMAGE_TAG $env:GITHUB_RUNNER_IMAGE_TAG
          azd env set GITHUB_RUNNER_IMAGE_BRANCH $env:GITHUB_RUNNER_IMAGE_BRANCH

          azd provision --no-prompt

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: success() || failure()
        with:
          name: sarif-reports
          path: |
            ./gitleaks-report.sarif
            ./checkov-results.sarif/results_sarif.sarif

      - name: Upload Gitleaks SARIF report to Github
        uses: github/codeql-action/upload-sarif@9b02dc2f60288b463e7a66e39c78829b62780db7 # v2.22.1
        with:
          sarif_file: ./gitleaks-report.sarif


      - name: Upload Checkov SARIF Report to GitHub
        uses: github/codeql-action/upload-sarif@9b02dc2f60288b463e7a66e39c78829b62780db7 # v2.22.1
        with:
          sarif_file: ./checkov-results.sarif/results_sarif.sarif


      - name: Azd down
        if: ${{ github.event.inputs.run_azd_down == true }}
        env:
         # POWER_PLATFORM_USE_CLI: false
          POWER_PLATFORM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          POWER_PLATFORM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

          ARM_USE_AZUREAD: "true"
          ARM_STORAGE_USE_AZUREAD: "true"
         # ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

          RS_STORAGE_ACCOUNT: ${{ vars.RS_STORAGE_ACCOUNT }}
          RS_CONTAINER_NAME: ${{ vars.RS_CONTAINER_NAME }}
          RS_RESOURCE_GROUP: ${{ vars.RS_RESOURCE_GROUP }}
          RESOURCE_SHARE_USER: ${{ vars.RESOURCE_SHARE_USER }}
         
         # POWER_PLATFORM_USE_OIDC: "true"
        shell: pwsh
        run: |

          azd env set RS_STORAGE_ACCOUNT $env:RS_STORAGE_ACCOUNT
          azd env set RS_CONTAINER_NAME $env:RS_CONTAINER_NAME
          azd env set RS_RESOURCE_GROUP $env:RS_RESOURCE_GROUP
          azd env set RESOURCE_SHARE_USER "$env:RESOURCE_SHARE_USER"

          azd env select $env:AZURE_ENV_NAME
          azd down --no-prompt --force --purge