name: Private Runner
permissions:
  contents: read
on:
 push:
   branches:
     - mattdot/private-runner    
 workflow_dispatch:
 
jobs: 
  test:
    runs-on: ${{ fromJson(vars.RUNNER_NAME || '["ubuntu-latest"]') }}
    steps:
      - name: Hello
        run: echo "hello private runner"
