name: "Deploy Terraform Remote State Infrastructure and GitHub runner"

on:
  workflow_dispatch:
    inputs:
      location:
        description: "Azure location for the tfstate and runner infrastructure"
        required: true
        default: "westus2"
      github_runner_type:
        description: "Type of GitHub runner to deploy"
        required: true
        type: choice
        options:
          - "vm"
          - "aca"
        default: "vm"
      github_runner_registration_token:
        description: The GitHub runner registration token for adding a new runner.  Get the token from repo settings > Actions > Runners > New self-hosted runner
        required: true

permissions:
  id-token: write
  contents: read
  actions: write

concurrency:
  group: "tfstate"
  cancel-in-progress: false # Do not cancel in-progress terraform runs

jobs:
  provision-remote-state:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cicd
    env:
      TF_IN_AUTOMATION: "true"
      ARM_USE_AZUREAD: "true"
      ARM_STORAGE_USE_AZUREAD: "true"
      ARM_USE_OIDC: "true"
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_subscription_id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_location: ${{ github.event.inputs.location }}
      TF_VAR_github_runner_type: ${{ github.event.inputs.github_runner_type }}
      TF_VAR_github_runner_config: >
        {
          "repo_owner": "${{ github.repository_owner }}",
          "repo_name": "${{ github.event.repository.name }}",
        }
    steps:
      - name: Mask sensitive input parameters
        uses: actions/github-script@v7
        with:
          script: |
            const token = context.payload?.inputs?.github_runner_registration_token || '';
            core.setSecret(token);                                                    
            core.exportVariable('TF_VAR_github_runner_registration_token', token); 

      - name: Checkout the branch ${{ github.ref_name }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref_name }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.12.2

      - name: Login to Azure with Federated Identity
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_github_pat: ${{ github.event.inputs.github_runner_type == 'aca' && secrets.GH_PAT || '' }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        run: terraform output

      - name: Cleanup plan file
        if: always()
        run: rm -f tfplan
